baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Weibiomed Co.Ltd"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/dall·e-2025-01-23-15.34.12-a-futuristic-ai-themed-background-design-featuring-a-glowing-neural-network-with-interconnected-nodes-and-circuits-a-holographic-globe-and-digital-.webp"]